[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_program = "2Mm6nxoHYXr4Fm6YHRCM8pdMJGe5a8vq55pYRGwCxYZj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/yogesh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
